Make sass dependency work on modern OSes
srobo/livestream-overlay pull request #11
Opened 2021-01-16 19:45 UTC by PeterJCLaw

Specifically on Ubuntu 20.04 there isn't Python 2 any more. Previously it seemed that the version of node-sass which was installed needed Python 2 as part of the build for node-gyp. This moves it to being a dev-dependency for clarity and then updates it to v5, which seems to avoid that issue.

2021-01-16 22:20 UTC, trickeydan approved these changes

2021-01-17 10:49 UTC, RealOrangeOne requested changes, later dismissed
`node-sass` is considered deprecated in favour of the Dart rewrite of sass, available on NPM under `sass`.

2021-01-17 11:50 UTC, trickeydan commented
> `node-sass` is considered deprecated in favour of the Dart rewrite of sass, available on NPM under `sass`.

This feels like it is probably out of scope for this PR and deserves it's own issue? Breaking changes etc etc

2021-01-20 21:03 UTC, PeterJCLaw commented
@RealOrangeOne thanks for the info, I wasn't aware of the sass changes. Do you feel strongly that we should hold up this PR on that basis? Currently I would push for getting this in because it does improve things, even if not perfectly.

2021-01-20 21:05 UTC, RealOrangeOne commented
I feel it should be done, but definitely not strongly enough to block this PR. Let's get this in, as currently I can't even build the application on my machine, and we can deal with deprecations at a later date!

2021-01-20 21:07 UTC, merged